name: Build and Upload APK

permissions:
  contents: write

on:
  push:
    branches: [master]
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-23.11

      - name: Submodules
        run: git submodule update --init

      - name: Signing
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > android/app/keystore.jks
          echo "storeFile=$(pwd)/android/app/keystore.jks" > android/key.properties
          echo "storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> android/key.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> android/key.properties

      - name: Doctor
        run: ./submodules/flutter/bin/flutter doctor
      - name: Config
        run: ./submodules/flutter/bin/flutter config --no-analytics
      - name: Dependencies
        run: ./submodules/flutter/bin/flutter pub get
      - name: Format
        run: ./submodules/flutter/bin/dart format --output=none --set-exit-if-changed ./lib
      - name: Analyze
        run: ./submodules/flutter/bin/dart analyze --no-fatal-warnings ./lib
      - name: Splash
        run: ./submodules/flutter/bin/flutter pub run flutter_native_splash:create

      - name: Build
        run: |
          export ANDROID_KEY_FILE=$(pwd)/android/key.properties
          ./submodules/flutter/bin/flutter build apk --release --split-per-abi

      - name: Upload
        uses: marvinpinto/action-automatic-releases@master
        with:
          title: "${{ github.event.repository.name }}"
          automatic_release_tag: "latest"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            build/app/outputs/flutter-apk/*.apk
